name: Lint PR

# Trigger the action on pull request creation targeting master branch
on:
  pull_request:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  lint:
    name: Run Prettier and ESLint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}

    # Install Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    # Install dependencies
    - name: Install dependencies
      run: npm ci

    # Run Prettier to check formatting
    - name: Run Prettier
      run: npm run prettier:check
      continue-on-error: true

    # Run ESLint to check for linting errors
    - name: Run ESLint
      run: npm run lint
      continue-on-error: true

    # Automatically fix the issues with Prettier
    - name: Run Prettier fix
      run: npm run prettier:write

    # Automatically fix the issues with ESLint
    - name: Run ESLint fix
      run: npm run lint:fix

    # Commit and stage changes if there are any
    - name: Commit and stage changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "chore: apply prettier/eslint fixes" || echo "No changes to commit"

    # Fetch the latest changes from master
    - name: Fetch latest changes
      run: git fetch origin master

    # Ensure we are on the right branch before rebasing
    - name: Checkout current branch
      run: git checkout ${{ github.head_ref }}

    # Rebase the latest changes from master into the feature branch
    - name: Pull and rebase with master
      run: |
        git rebase origin/master || git rebase --abort

    # Push changes back to the PR branch if any fixes were applied
    - name: Push changes back to PR branch
      run: |
        git push --force origin HEAD:${{ github.head_ref }}
      if: success()
