name: Lint PR

# Trigger the action on pull request creation targeting master branch
on:
  pull_request:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  lint:
    name: Run Prettier and ESLint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Install Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Install dependencies
    - name: Install dependencies
      run: npm ci

    # Run Prettier to check formatting
    - name: Run Prettier
      run: npm run prettier:check
      continue-on-error: true

    # Run ESLint to check for linting errors
    - name: Run ESLint
      run: npm run lint
      continue-on-error: true

    # Optionally, if you want to automatically fix the issues:
    - name: Run Prettier fix
      run: npm run prettier:write

    - name: Run ESLint fix
      run: npm run lint:fix

    - name: Commit and stage changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "chore: apply prettier/eslint fixes" || echo "No changes to commit"

    - name: Pull and rebase
      run: |
        git pull --rebase origin ${{ github.ref }}

    # Commit and push changes back to the PR branch if any fixes were applied
    - name: Push changes back to PR branch
      run: |
        
        git push origin HEAD:${{ github.head_ref }}
      if: success()